'use client';

import { useState } from 'react';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { getNutritionalData } from '@/app/actions';
import type { NutritionalInformationOutput } from '@/ai/flows/nutritional-information-from-ingredients';
import { Loader2, Flame, Beef, Wheat, Droplets } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

type NutritionalInfoProps = {
  ingredients: string[];
};

export default function NutritionalInfo({ ingredients }: NutritionalInfoProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<NutritionalInformationOutput | null>(null);
  const { toast } = useToast();

  const handleFetchNutritionalInfo = async () => {
    setLoading(true);
    setError(null);
    setData(null);

    const result = await getNutritionalData(ingredients);

    if (result.success && result.data) {
      setData(result.data);
    } else {
      setError(result.error || 'An unknown error occurred.');
      toast({
        variant: 'destructive',
        title: 'Oh no! Something went wrong.',
        description: result.error || 'Could not fetch nutritional information.',
      });
    }

    setLoading(false);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Nutritional Info</CardTitle>
        <CardDescription>
          Approximate values per serving, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {data ? (
          <div className="grid grid-cols-2 gap-4 text-center">
            <div className="bg-muted/50 p-3 rounded-lg">
              <Flame className="mx-auto h-6 w-6 mb-1 text-accent" />
              <p className="font-bold text-lg">{data.calories}</p>
              <p className="text-sm text-muted-foreground">Calories</p>
            </div>
            <div className="bg-muted/50 p-3 rounded-lg">
              <Beef className="mx-auto h-6 w-6 mb-1 text-accent" />
              <p className="font-bold text-lg">{data.protein}</p>
              <p className="text-sm text-muted-foreground">Protein</p>
            </div>
            <div className="bg-muted/50 p-3 rounded-lg">
              <Wheat className="mx-auto h-6 w-6 mb-1 text-accent" />
              <p className="font-bold text-lg">{data.carbs}</p>
              <p className="text-sm text-muted-foreground">Carbs</p>
            </div>
            <div className="bg-muted/50 p-3 rounded-lg">
              <Droplets className="mx-auto h-6 w-6 mb-1 text-accent" />
              <p className="font-bold text-lg">{data.fat}</p>
              <p className="text-sm text-muted-foreground">Fat</p>
            </div>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">
            Click the button below to calculate the estimated nutritional information for this recipe.
          </p>
        )}
      </CardContent>
      <CardFooter>
        <Button
          onClick={handleFetchNutritionalInfo}
          disabled={loading}
          className="w-full"
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Calculating...
            </>
          ) : (
            'Calculate'
          )}
        </Button>
      </CardFooter>
    </Card>
  );
}
