'use client';

import { Beef, Droplets, Flame, Loader2, Wheat } from 'lucide-react';
import { useState } from 'react';

import type { NutritionalInformationOutput } from '@/ai/flows/nutritional-information-from-ingredients';
import { getNutritionalData } from '@/app/actions';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';

type NutritionalInfoProps = {
  ingredients: string[];
};

export default function NutritionalInfo({ ingredients }: NutritionalInfoProps) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<NutritionalInformationOutput | null>(null);
  const { toast } = useToast();

  const handleFetchNutritionalInfo = async () => {
    setLoading(true);
    setError(null);
    setData(null);

    try {
      const result = await getNutritionalData(ingredients);

      if (result.success && result.data) {
        setData(result.data);
      } else {
        setError(result.error || 'An unknown error occurred.');
        toast({
          variant: 'destructive',
          title: 'Oh no! Something went wrong.',
          description: result.error || 'Could not fetch nutritional information.',
        });
      }
    } catch (error) {
      console.error('Error fetching nutritional data:', error);
      setError(error instanceof Error ? error.message : String(error));
      toast({
        variant: 'destructive',
        title: 'Error',
        description:
          error instanceof Error ? error.message : 'Failed to fetch nutritional information.',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Nutritional Info</CardTitle>
        <CardDescription>Approximate values per serving, generated by AI.</CardDescription>
      </CardHeader>
      <CardContent>
        {data ? (
          <div className="grid grid-cols-2 gap-4 text-center">
            <div className="rounded-lg bg-muted/50 p-3">
              <Flame className="mx-auto mb-1 h-6 w-6 text-accent" />
              <p className="text-lg font-bold">{data.calories}</p>
              <p className="text-sm text-muted-foreground">Calories</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3">
              <Beef className="mx-auto mb-1 h-6 w-6 text-accent" />
              <p className="text-lg font-bold">{data.protein}</p>
              <p className="text-sm text-muted-foreground">Protein</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3">
              <Wheat className="mx-auto mb-1 h-6 w-6 text-accent" />
              <p className="text-lg font-bold">{data.carbs}</p>
              <p className="text-sm text-muted-foreground">Carbs</p>
            </div>
            <div className="rounded-lg bg-muted/50 p-3">
              <Droplets className="mx-auto mb-1 h-6 w-6 text-accent" />
              <p className="text-lg font-bold">{data.fat}</p>
              <p className="text-sm text-muted-foreground">Fat</p>
            </div>
          </div>
        ) : (
          <>
            {error && <div className="mb-2 text-sm text-destructive">Error: {error}</div>}
            <p className="text-sm text-muted-foreground">
              Click the button below to calculate the estimated nutritional information for this
              recipe.
            </p>
          </>
        )}
      </CardContent>
      <CardFooter>
        <Button onClick={handleFetchNutritionalInfo} disabled={loading} className="w-full">
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Calculating...
            </>
          ) : (
            'Calculate'
          )}
        </Button>
      </CardFooter>
    </Card>
  );
}
